// Code generated by scripts/gen_layer3.go — DO NOT EDIT.
//
// Source: internal/tools/*.go (Definition().Name extracted via go/ast).
// Per ADR-018 single-source-of-truth: regenerate via
//   go run floworkos-go/scripts/gen_layer3.go --target=registry_const --apply
// Last gen: 2026-05-08T07:23:38Z

package tools

const (
	ToolAgentTaskGet = "agent_task_get"  // AgentTaskGetTool
	ToolAgentTaskList = "agent_task_list"  // AgentTaskListTool
	ToolAgentTaskOutput = "agent_task_output"  // AgentTaskOutputTool
	ToolAlertOwner = "alert_owner"  // AlertOwnerTool
	ToolAskuserquestion = "askuserquestion"  // AskUserQuestionTool
	ToolBash = "bash"  // BashTool
	ToolBrainGetDrawer = "brain_get_drawer"  // BrainGetDrawerTool
	ToolBrainRecall = "brain_recall"  // BrainRecallTool
	ToolBrainSearch = "brain_search"  // BrainSearchTool
	ToolBrief = "brief"  // BriefTool
	ToolBrowserClick = "browser_click"  // BrowserClickTool
	ToolBrowserDragDrop = "browser_drag_drop"  // BrowserDragDropTool
	ToolBrowserExtract = "browser_extract"  // BrowserExtractTool
	ToolBrowserNavigate = "browser_navigate"  // BrowserNavigateTool
	ToolBrowserOpen = "browser_open"  // BrowserOpenTool
	ToolBrowserRender = "browser_render"  // BrowserRenderTool
	ToolBrowserSearch = "browser_search"  // BrowserSearchTool
	ToolBrowserType = "browser_type"  // BrowserTypeTool
	ToolBugReport = "bug_report"  // BugReportTool
	ToolChangeLogPost = "change_log_post"  // ChangeLogPostTool
	ToolCodeFlowTrace = "code_flow_trace"  // CodeFlowTraceTool
	ToolCodeGraphQuery = "code_graph_query"  // CodeGraphQueryTool
	ToolCodeReviewContext = "code_review_context"  // CodeReviewContextTool
	ToolCodemapDeps = "codemap_deps"  // CodemapDepsTool
	ToolCodemapHealth = "codemap_health"  // CodemapHealthTool
	ToolCodemapImpact = "codemap_impact"  // CodemapImpactTool
	ToolCodemapSearch = "codemap_search"  // CodemapSearchTool
	ToolCodemapZombies = "codemap_zombies"  // CodemapZombiesTool
	ToolConfig = "config"  // ConfigTool
	ToolCronCreate = "cron_create"  // CronCreateTool
	ToolCronDelete = "cron_delete"  // CronDeleteTool
	ToolCronList = "cron_list"  // CronListTool
	ToolDeathLetterRead = "death_letter_read"  // DeathLetterReadTool
	ToolDeathLetterWrite = "death_letter_write"  // DeathLetterWriteTool
	ToolEdit = "edit"  // EditTool
	ToolEnterPlanMode = "enter_plan_mode"  // EnterPlanModeTool
	ToolEnterWorktree = "enter_worktree"  // EnterWorktreeTool
	ToolExitPlanMode = "exit_plan_mode"  // ExitPlanModeTool
	ToolExitWorktree = "exit_worktree"  // ExitWorktreeTool
	ToolFacebookPostStatus = "facebook_post_status"  // FacebookPostStatusTool
	ToolFactForget = "fact_forget"  // FactForgetTool
	ToolFactRecall = "fact_recall"  // FactRecallTool
	ToolFactRemember = "fact_remember"  // FactRememberTool
	ToolFindCallers = "find_callers"  // FindCallersTool
	ToolGetDoktrin = "get_doktrin"  // GetDoktrinTool
	ToolGetExternalTraining = "get_external_training"  // GetExternalTrainingTool
	ToolGetKarma = "get_karma"  // GetKarmaTool
	ToolGetProtectedCoreList = "get_protected_core_list"  // GetProtectedCoreListTool
	ToolGetSecretMasked = "get_secret_masked"  // GetSecretMaskedTool
	ToolGit = "git"  // GitTool
	ToolGitCheckpoint = "git_checkpoint"  // GitCheckpointTool
	ToolGitRollback = "git_rollback"  // GitRollbackTool
	ToolGitVerify = "git_verify"  // GitVerifyTool
	ToolGlob = "glob"  // GlobTool
	ToolGoalDone = "goal_done"  // GoalDoneTool
	ToolGrep = "grep"  // GrepTool
	ToolList = "list"  // ListTool
	ToolListExternalTraining = "list_external_training"  // ListExternalTrainingTool
	ToolListMyTools = "list_my_tools"  // ListMyToolsTool
	ToolListRoles = "list_roles"  // ListRolesTool
	ToolListSecretsMasked = "list_secrets_masked"  // ListSecretsMaskedTool
	ToolLsp = "lsp"  // LSPTool
	ToolMagicDocs = "magic_docs"  // MagicDocsTool
	ToolMcpAuth = "mcp_auth"  // McpAuthTool
	ToolMcpCall = "mcp_call"  // MCPTool
	ToolMcpListResources = "mcp_list_resources"  // MCPListResourcesTool
	ToolMcpReadResource = "mcp_read_resource"  // MCPReadResourceTool
	ToolMemoryDelete = "memory_delete"  // MemoryDeleteTool
	ToolMemoryGet = "memory_get"  // MemoryGetTool
	ToolMemorySet = "memory_set"  // MemorySetTool
	ToolMonitor = "monitor"  // MonitorTool
	ToolMultiedit = "multiedit"  // MultiEditTool
	ToolMusicArtistAdd = "music_artist_add"  // MusicArtistAddTool
	ToolMusicArtistList = "music_artist_list"  // MusicArtistListTool
	ToolMusicPipelineStatus = "music_pipeline_status"  // MusicPipelineStatusTool
	ToolNotebookedit = "notebookedit"  // NotebookEditTool
	ToolPeerReview = "peer_review"  // PeerReviewTool
	ToolPlanRead = "plan_read"  // PlanReadTool
	ToolPlanWrite = "plan_write"  // PlanWriteTool
	ToolPowershell = "powershell"  // PowerShellTool
	ToolRead = "read"  // ReadTool
	ToolRemoteTrigger = "remote_trigger"  // RemoteTriggerTool
	ToolRepl = "repl"  // REPLTool
	ToolRunSandboxCommand = "run_sandbox_command"  // SandboxTool
	ToolScreenshot = "screenshot"  // BrowserScreenshotTool
	ToolSearchSemanticFunction = "search_semantic_function"  // AstSearchTool
	ToolSendMessage = "send_message"  // SendMessageTool
	ToolSkill = "skill"  // SkillTool
	ToolSkillSearch = "skill_search"  // SkillSearchTool
	ToolSkillWrite = "skill_write"  // SkillWriteTool
	ToolSleep = "sleep"  // SleepTool
	ToolSnip = "snip"  // SnipTool
	ToolStructuredOutput = "structured_output"  // StructuredOutputTool
	ToolTask = "task"  // TaskTool
	ToolTaskCreate = "task_create"  // TaskCreateTool
	ToolTaskGet = "task_get"  // TaskGetTool
	ToolTaskList = "task_list"  // TaskListTool
	ToolTaskOutput = "task_output"  // TaskOutputTool
	ToolTaskParallel = "task_parallel"  // TaskParallelTool
	ToolTaskStop = "task_stop"  // TaskStopTool
	ToolTelegramSend = "telegram_send"  // TelegramSendTool
	ToolTicketCreate = "ticket_create"  // TicketCreateTool
	ToolTodo = "todo"  // TodoTool
	ToolToolPropose = "tool_propose"  // ToolProposeTool
	ToolToolSearch = "tool_search"  // ToolSearchTool
	ToolVerifyPlanExecution = "verify_plan_execution"  // VerifyPlanExecutionTool
	ToolWebfetch = "webfetch"  // WebFetchTool
	ToolWebsearch = "websearch"  // WebSearchTool
	ToolWorkflow = "workflow"  // WorkflowTool
	ToolWrite = "write"  // WriteTool
)

// AllToolNames returns canonical tool name list (sorted).
// Used by drift scanner + Phase 4 schema migration.
func AllToolNames() []string {
	return []string{
		"agent_task_get",
		"agent_task_list",
		"agent_task_output",
		"alert_owner",
		"askuserquestion",
		"bash",
		"brain_get_drawer",
		"brain_recall",
		"brain_search",
		"brief",
		"browser_click",
		"browser_drag_drop",
		"browser_extract",
		"browser_navigate",
		"browser_open",
		"browser_render",
		"browser_search",
		"browser_type",
		"bug_report",
		"change_log_post",
		"code_flow_trace",
		"code_graph_query",
		"code_review_context",
		"codemap_deps",
		"codemap_health",
		"codemap_impact",
		"codemap_search",
		"codemap_zombies",
		"config",
		"cron_create",
		"cron_delete",
		"cron_list",
		"death_letter_read",
		"death_letter_write",
		"edit",
		"enter_plan_mode",
		"enter_worktree",
		"exit_plan_mode",
		"exit_worktree",
		"facebook_post_status",
		"fact_forget",
		"fact_recall",
		"fact_remember",
		"find_callers",
		"get_doktrin",
		"get_external_training",
		"get_karma",
		"get_protected_core_list",
		"get_secret_masked",
		"git",
		"git_checkpoint",
		"git_rollback",
		"git_verify",
		"glob",
		"goal_done",
		"grep",
		"list",
		"list_external_training",
		"list_my_tools",
		"list_roles",
		"list_secrets_masked",
		"lsp",
		"magic_docs",
		"mcp_auth",
		"mcp_call",
		"mcp_list_resources",
		"mcp_read_resource",
		"memory_delete",
		"memory_get",
		"memory_set",
		"monitor",
		"multiedit",
		"music_artist_add",
		"music_artist_list",
		"music_pipeline_status",
		"notebookedit",
		"peer_review",
		"plan_read",
		"plan_write",
		"powershell",
		"read",
		"remote_trigger",
		"repl",
		"run_sandbox_command",
		"screenshot",
		"search_semantic_function",
		"send_message",
		"skill",
		"skill_search",
		"skill_write",
		"sleep",
		"snip",
		"structured_output",
		"task",
		"task_create",
		"task_get",
		"task_list",
		"task_output",
		"task_parallel",
		"task_stop",
		"telegram_send",
		"ticket_create",
		"todo",
		"tool_propose",
		"tool_search",
		"verify_plan_execution",
		"webfetch",
		"websearch",
		"workflow",
		"write",
	}
}
