// AUTO-GENERATED by tool_create (sidecar self-evolving). Badan run() dari agent.
package main

import (
	"encoding/json"
	"io"
	"os"
)

// run — LOGIC dari agent. args = param dari pemanggil; balikin (output, errString).
func run(args map[string]any) (any, string) {
t,_ := args["text"].(string)
 if t=="" { return nil,"text wajib" }
 r := []rune(t)
 for i,j:=0,len(r)-1; i<j; i,j=i+1,j-1 { r[i],r[j]=r[j],r[i] }
 return map[string]any{"reversed":string(r)},""
}

func main() {
	var req struct {
		Args map[string]any `json:"args"`
	}
	in, _ := io.ReadAll(os.Stdin)
	_ = json.Unmarshal(in, &req)
	if req.Args == nil {
		req.Args = map[string]any{}
	}
	o, e := run(req.Args)
	b, _ := json.Marshal(map[string]any{"output": o, "error": e})
	_, _ = os.Stdout.Write(b)
}
